In [4]:
print("Question 1")
import numpy as np

array = np.arange(2,50,3)

print(array)

print('\n---------------------------\n')

Question 1
[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]

---------------------------



In [15]:
print("Question 2")
import numpy as np
lst_1 = []
lst_2 = []
print("Enter 5 elements for list 1")
for i in range(5):
    inp = int(input())
    lst_1.append(inp)
print("Enter 5 elements for list 2")
for i in range(5):
    inp = int(input())
    lst_2.append(inp)
arr_1 = np.array(lst_1)
arr_2 = np.array(lst_2)
concat_arr = np.concatenate((arr_1,arr_2))
print(concat_arr)
print("\n")
print(np.sort(concat_arr))
print('\n---------------------------\n')

Question 2
Enter 5 elements for list 1
10
20
30
40
50
Enter 5 elements for list 2
60
70
80
90
100
[ 10  20  30  40  50  60  70  80  90 100]


[ 10  20  30  40  50  60  70  80  90 100]

---------------------------



In [10]:
print("Question 3")
import numpy as np

arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
print("Dimension of an array:",arr.ndim)
print("Size of an array:",arr.size)

print('\n---------------------------\n')


Question 3
Dimension of an array: 2
Size of an array: 9

---------------------------



In [12]:
print("Question 4")
import numpy as dp

arr = dp.arange(int(input()))
print("Test 1D array (shape) :", arr.shape)

D2_arr_row = arr[dp.newaxis]
print("2D array for row is :", D2_arr_row.shape)

D2_arr_column = arr[:, dp.newaxis]
print("2D array for column is :", D2_arr_column.shape)
print('\n---------------------------\n')


Question 4
31
Test 1D array (shape) : (31,)
2D array for row is : (1, 31)
2D array for column is : (31, 1)

---------------------------



In [13]:
print("Question 5")
import numpy as np

arr_1 = np.square([1,3,5,7,9]) 
arr_2 = np.square([2,4,6,8,10])


print(" horizontally stacked : \n", np.hstack((arr_1, arr_2)))
print("\n")

print("vertically stacked : \n", np.vstack((arr_1, arr_2)))
print('\n---------------------------\n')


Question 5
 horizontally stacked : 
 [  1   9  25  49  81   4  16  36  64 100]


vertically stacked : 
 [[  1   9  25  49  81]
 [  4  16  36  64 100]]

---------------------------



In [14]:
print("Question 6")
import numpy as np

arr = np.array([5, 7, 8, 9, 5, 6, 5, 4, 4])

unique, counts = np.unique(arr, return_counts=True)
arr = np.asarray((unique, counts)).T
print(arr)
print('\n---------------------------\n')

Question 6
[[4 2]
 [5 3]
 [6 1]
 [7 1]
 [8 1]
 [9 1]]

---------------------------

